name: bigquery
operator_class: BigQueryOperator
operator_class_module: airflow.contrib.operators.bigquery_operator
schema_extends: base

parameters_jsonschema:
  properties:
    bql:
      type: string
      additionalProperties:
        type: array
        items:
          type: string
    sql:
      type: string
      additionalProperties:
        type: array
        items:
          type: string
    destination_dataset_table:
      type: string
    write_disposition:
      type: string
    create_disposition:
      type: string
    allow_large_results:
      type: boolean
    flatten_results:
      type: boolean
    bigquery_conn_id:
      type: string
    delegate_to:
      type: string
    udf_config:
      type: array
      items:
        type: string
    use_legacy_sql:
      type: boolean
    maximum_billing_tier:
      type: integer
    maximum_bytes_billed:
      type: number
    api_resource_configs:
      type: object
    schema_update_options:
      type: object
    query_params:
      type: array
      items:
        type: object
    labels:
      type: object
    priority:
      type: string
    time_partitioning:
      type: object
    cluster_fields:
      type: array
      items:
        type: string
    location:
      type: string
    encryption_configuration:
      type: object
    retry_delay:
      type: string
      format: date-time
  additionalProperties: false